// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Future = require("reason-future/src/Future.bs.js");
var Graphql_Schema = require("../Graphql_Schema.bs.js");

var Schema = Graphql_Schema.Make({
      $$return: Future.value,
      bind: Future.flatMap
    });

var Language = /* alias */0;

exports.Schema = Schema;
exports.Language = Language;
/* Schema Not a pure module */
