// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Graphql_Schema = require("../Graphql_Schema.bs.js");

function $$return(prim) {
  return Promise.resolve(prim);
}

function bind(p, continuation) {
  return p.then(Curry.__1(continuation));
}

var Schema = Graphql_Schema.Make({
      $$return: $$return,
      bind: bind
    });

var Language = /* alias */0;

exports.Schema = Schema;
exports.Language = Language;
/* Schema Not a pure module */
