// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Promise = require("reason-promise/src/js/promise.js");
var Graphql_Schema = require("../Graphql_Schema.bs.js");

var Schema = Graphql_Schema.Make({
      $$return: $$Promise.resolved,
      bind: $$Promise.flatMap
    });

var Language = /* alias */0;

exports.Schema = Schema;
exports.Language = Language;
/* Schema Not a pure module */
