// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Schema = /* alias */0;

var Language = /* alias */0;

var Json = /* alias */0;

exports.Schema = Schema;
exports.Language = Language;
exports.Json = Json;
/* No side effect */
